services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bank-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bank-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8090:8080"
    networks:
      - bank-net

  redis:
    image: redis:7-alpine
    networks:
      - bank-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./infrastructure/keycloak/digital-banking-realm.json:/opt/keycloak/data/import/digital-banking-realm.json:ro
    ports:
      - "8180:8080"
    networks:
      - bank-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/scripts/init-postgres.sql:/docker-entrypoint-initdb.d/01-init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bank-net

  core-simulator:
    build: ./backend/core-simulator
    networks:
      - bank-net

  fraud-detection-service:
    build:
      context: ./backend
      dockerfile: fraud-detection-service/Dockerfile
    depends_on:
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - bank-net

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    depends_on:
      kafka:
        condition: service_started
      mailhog:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: "1025"
      NOTIFICATION_EMAIL_ENABLED: "true"
    networks:
      - bank-net

  account-service:
    build:
      context: ./backend
      dockerfile: account-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
      core-simulator:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DAY2_KAFKA_CONSUMER_ENABLED: "true"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_CACHE_TYPE: redis
      CORE_INTEGRATION_ENABLED: "true"
      CORE_INTEGRATION_BASE_URL: http://core-simulator:8087
    networks:
      - bank-net

  transaction-service:
    build:
      context: ./backend
      dockerfile: transaction-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      account-service:
        condition: service_started
      fraud-detection-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      ACCOUNT_SERVICE_BASE_URL: http://account-service:8081
      DAY2_KAFKA_PRODUCER_ENABLED: "true"
      FRAUD_EVALUATION_ENABLED: "true"
      FRAUD_EVALUATION_BASE_URL: http://fraud-detection-service:8088
    networks:
      - bank-net

  openbanking-service:
    build: ./backend/openbanking-service
    depends_on:
      postgres:
        condition: service_healthy
      account-service:
        condition: service_started
      transaction-service:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ACCOUNT_SERVICE_BASE_URL: http://account-service:8081
      TRANSACTION_SERVICE_BASE_URL: http://transaction-service:8082
    networks:
      - bank-net

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - transaction-service
      - openbanking-service
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      GATEWAY_ACCOUNT_URI: http://account-service:8081
      GATEWAY_TRANSACTION_URI: http://transaction-service:8082
      GATEWAY_OPENBANKING_URI: http://openbanking-service:8083
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3010,http://localhost:19006
      GATEWAY_CHANNEL_VALIDATION_ENABLED: "true"
    networks:
      - bank-net

  mobile-web:
    build:
      context: ./frontend/mobile-app
      args:
        EXPO_PUBLIC_GATEWAY_URL: http://localhost:8080
    ports:
      - "3010:3010"
    depends_on:
      - api-gateway
    networks:
      - bank-net

  web-portal:
    build:
      context: ./frontend/web-portal
      args:
        REACT_APP_GATEWAY_URL: http://localhost:8080
        REACT_APP_KEYCLOAK_URL: http://localhost:8180
        REACT_APP_KEYCLOAK_REALM: digital-banking
        REACT_APP_KEYCLOAK_CLIENT_ID: web-portal
        REACT_APP_MOCK_CUSTOMER_ID: open-sample-uk-001
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
      - keycloak
    networks:
      - bank-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - bank-net

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./infrastructure/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - api-gateway
    networks:
      - bank-net

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./infrastructure/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - bank-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - bank-net

networks:
  bank-net:
    driver: bridge

volumes:
  postgres_data:
