services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bank-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bank-net

  redis:
    image: redis:7-alpine
    networks:
      - bank-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/scripts/init-postgres.sql:/docker-entrypoint-initdb.d/01-init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bank-net

  account-service:
    build: ./backend/account-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bank-net

  transaction-service:
    build: ./backend/transaction-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bank-net

  openbanking-service:
    build: ./backend/openbanking-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - bank-net

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - transaction-service
      - openbanking-service
    environment:
      GATEWAY_ACCOUNT_URI: http://account-service:8081
      GATEWAY_TRANSACTION_URI: http://transaction-service:8082
      GATEWAY_OPENBANKING_URI: http://openbanking-service:8083
    networks:
      - bank-net

  web-portal:
    build: ./frontend/web-portal
    ports:
      - "3000:3000"
    environment:
      REACT_APP_GATEWAY_URL: http://localhost:8080
      CI: "true"
    stdin_open: true
    tty: true
    depends_on:
      - api-gateway
    networks:
      - bank-net

networks:
  bank-net:
    driver: bridge

volumes:
  postgres_data:
