apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
