server:
  port: 8088

spring:
  application:
    name: fraud-detection-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: fraud-detection
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

day3:
  kafka:
    topics:
      transaction-created: bank.transaction.created

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
