server:
  port: 8083

spring:
  application:
    name: openbanking-service
  datasource:
    url: jdbc:h2:mem:ob;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

spring.security.oauth2.resourceserver.jwt.issuer-uri: ${KEYCLOAK_ISSUER_URI:}

account.service.base-url: ${ACCOUNT_SERVICE_BASE_URL:}
transaction.service.base-url: ${TRANSACTION_SERVICE_BASE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
