server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:tx;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
